services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=testdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3355:3306'
