spring:
  datasource:
    url: jdbc:mysql://localhost:3355/testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  docker:
    compose:
      lifecycle-management: start_only


security:
  jwt:
    secret: secret-key
    expires-in-seconds: 3600
